# Change these first
owner: mkevenaar-docktera # Your GitHub organization or username, where this repository lives
repo: status.docktera.net # The name of this repository

sites:
  - name: DOCKTERA
    url: https://www.docktera.com
  - name: DOCKTERA PaaS
    url: https://app.jls.docktera.net
  - name: my DOCKTERA
    url: https://my.docktera.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.docktera.net
  # baseUrl: /your-repo-name
  logoUrl: https://www.docktera.com/wp-content/uploads/logo-272x39.png
  favicon: https://www.docktera.com/wp-content/uploads/favicon.ico
  name: DOCKTERA
  introTitle: "DOCKTERA status page"
  introMessage: Welcome, check out our services current uptime below.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
